## Mapping

In [1]:
m = map(lambda a: a*a, [1,2,3,4,5])
list(m)

[1, 4, 9, 16, 25]

## Filter

In [2]:
#The filter() method filters the given sequence with the help of a function that tests each element in the sequence to be true or not. 

In [3]:
def is_odd(x):
    if x%2==1:
        return True
    else:
        return False

f = filter(is_odd, [1,2,3,4,5,6])
list(f)

[1, 3, 5]

# Numpy

In [4]:
# array proccessing package
l = [[1,1], [2,2], [3,5], [4,5]]
l

[[1, 1], [2, 2], [3, 5], [4, 5]]

In [5]:
 import numpy as np 

In [6]:
np_arr = np.array(l)
np_arr

array([[1, 1],
       [2, 2],
       [3, 5],
       [4, 5]])

In [7]:
type(l), type(np_arr)

(list, numpy.ndarray)

In [8]:
ls1 = [1,2,3,4]
ls2 = [2,2,10,4]
ls3 = [3,2,3,4]

merged = np.array([ls1, ls2, ls3])
merged

array([[ 1,  2,  3,  4],
       [ 2,  2, 10,  4],
       [ 3,  2,  3,  4]])

In [9]:
merged.shape

(3, 4)

In [10]:
merged[1][2]

10

In [11]:
merged[1:]

array([[ 2,  2, 10,  4],
       [ 3,  2,  3,  4]])

In [12]:
merged[:1,2:]

array([[3, 4]])

In [13]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.ones((2,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
np.zeros((2,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
n = np.arange(10,20)
n.reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Pandas

In [17]:
import pandas as pd

In [18]:
df = pd.DataFrame(np.arange(0,30).reshape(5,6), index=['R1','R2','R3','R4','R5'], columns= ['C1','C2','C3','C4','C5','C6'])

In [19]:
df

C1  C2  C3  C4  C5  C6
R1   0   1   2   3   4   5
R2   6   7   8   9  10  11
R3  12  13  14  15  16  17
R4  18  19  20  21  22  23
R5  24  25  26  27  28  29

In [20]:
df.head(3) #first 3

C1  C2  C3  C4  C5  C6
R1   0   1   2   3   4   5
R2   6   7   8   9  10  11
R3  12  13  14  15  16  17

In [21]:
df.tail(3) #last 3

C1  C2  C3  C4  C5  C6
R3  12  13  14  15  16  17
R4  18  19  20  21  22  23
R5  24  25  26  27  28  29

In [22]:
df.loc['R1']

C1    0
C2    1
C3    2
C4    3
C5    4
C6    5
Name: R1, dtype: int32

In [23]:
#slicing
df.iloc[:2,:3]

C1  C2  C3
R1   0   1   2
R2   6   7   8

In [24]:
df.values           #converting into array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [30]:
df_mb = pd.read_csv("CSE 19_A.csv")
df_mb.head(10)

Serial  Roll No           Student Name  Contact No  \
0       1  1903001      Saniul Islam Anik  1798298817   
1       2  1903002          Md. Sumon Ali  1794108082   
2       3  1903003  Afifa Tasneem Quanita  1764828065   
3       4  1903004         Sheikh Zubayer  1521576104   
4       5  1903005       Arpon Biswas Joy  1881010327   
5       6  1903006          Sayeef Mahmud  1521102917   
6       7  1903007   Sheikh Rabeya Shakil  1753249866   
7       8  1903008      Srabony Rani Paul  1763786707   
8       9  1903009       Onik Jahan Sagor  1882692449   
9      10  1903010  Naimur Hassan Swapnil  1773144638   

               Email Address  
0       orionrigel@gmail.com  
1     sumonali7656@gmail.com  
2   afifaquanita25@gmail.com  
3     bdksheikh007@gmail.com  
4         abjoy852@gmail.com  
5      smahmud2866@gmail.com  
6  sheikhtisha2000@gmail.com  
7   srabonypaul637@gmail.com  
8     priencesagor@gmail.com  
9     alvihassan61@gmail.com

In [31]:
df_mb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Serial         60 non-null     int64 
 1   Roll No        60 non-null     int64 
 2   Student Name   60 non-null     object
 3   Contact No     60 non-null     int64 
 4   Email Address  60 non-null     object
dtypes: int64(3), object(2)
memory usage: 2.5+ KB


In [32]:
df_mb.describe()

Serial       Roll No    Contact No
count  60.000000  6.000000e+01  6.000000e+01
mean   30.500000  1.903030e+06  1.742765e+09
std    17.464249  1.746425e+01  1.706998e+08
min     1.000000  1.903001e+06  1.303215e+09
25%    15.750000  1.903016e+06  1.707497e+09
50%    30.500000  1.903030e+06  1.762705e+09
75%    45.250000  1.903045e+06  1.845393e+09
max    60.000000  1.903060e+06  1.996111e+09

In [34]:
df_mb['Roll No']

0     1903001
1     1903002
2     1903003
3     1903004
4     1903005
5     1903006
6     1903007
7     1903008
8     1903009
9     1903010
10    1903011
11    1903012
12    1903013
13    1903014
14    1903015
15    1903016
16    1903017
17    1903018
18    1903019
19    1903020
20    1903021
21    1903022
22    1903023
23    1903024
24    1903025
25    1903026
26    1903027
27    1903028
28    1903029
29    1903030
30    1903031
31    1903032
32    1903033
33    1903034
34    1903035
35    1903036
36    1903037
37    1903038
38    1903039
39    1903040
40    1903041
41    1903042
42    1903043
43    1903044
44    1903045
45    1903046
46    1903047
47    1903048
48    1903049
49    1903050
50    1903051
51    1903052
52    1903053
53    1903054
54    1903055
55    1903056
56    1903057
57    1903058
58    1903059
59    1903060
Name: Roll No, dtype: int64

In [36]:
df_mb[df_mb['Roll No']>1903050]

Serial  Roll No            Student Name  Contact No  \
50      51  1903051       Rishat Bin Nashir  1308227589   
51      52  1903052   Khandker Moniruzzaman  1904159229   
52      53  1903053          Noshin Tamanna  1945137331   
53      54  1903054              Rakesh Kar  1991953354   
54      55  1903055      Fariha Binte Tarik  1707431949   
55      56  1903056          Mahib uz Zaman  1841787373   
56      57  1903057     Asifur Rahman Rahat  1753888810   
57      58  1903058  Dipanjan Karmaker Amit  1685294759   
58      59  1903059     Raiyan Mostofa Yead  1924446697   
59      60  1903060           Sadia Murshid  1756206583   

                   Email Address  
50   rishatbinnashir11@gmail.com  
51          kmsehab130@gmail.com  
52    noshintamanna810@gmail.com  
53       rakeshkar2000@gmail.com  
54      bintetarikh001@gmail.com  
55  ashfaqulbhuiyan123@gmail.com  
56         asifrahat99@gmail.com  
57    dipanjankarmaker@gmail.com  
58       raiyanyead124@gmail.com  
59     sadiamurshid148@gmail.com

In [37]:
df_mb.corr()

C:\Users\User\AppData\Local\Temp\ipykernel_18580\3470302100.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_mb.corr()


Serial   Roll No  Contact No
Serial      1.000000  1.000000    0.124805
Roll No     1.000000  1.000000    0.124805
Contact No  0.124805  0.124805    1.000000

# Json, HTML, Pickle

In [40]:
info = pd.read_csv('CSE 19_B.data')
info.head()

FileNotFoundError: [Errno 2] No such file or directory: 'CSE 19_B.data'

In [ ]:
#Pickling

